DESIGN_NAME: rd_5_32

VERILOG_FILES:
  - dir::rd_5_32.sv
  - dir::rd_2_4.sv
  - dir::rd_3_8.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 25

PRIMARY_GDSII_STREAMOUT_TOOL: klayout

PNR_SDC_FILE: dir::constraints.sdc

STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu7t5v0
TECH_LEFS: 
    "nom_*": "pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0__nom.tlef"


# PDK / stdcell libraryâ€“specific settings
pdk::gf180mcuD:
  scl::gf180mcu_fd_sc_mcu7t5v0:

    # Use only this timing corner
    DEFAULT_CORNER: nom_tt_025C_3v30
    STA_CORNERS: [nom_tt_025C_3v30]

    # Point that corner to a specific .lib
    LIB:
      nom_tt_025C_3v30:
        - "pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_3v30.lib"

# Pin Order
FP_PIN_ORDER_CFG: dir::pin_order.cfg

# Pin metal layer
FP_IO_HLAYER: "Metal3"
FP_IO_HEXTEND: 2.0

# Area
FP_SIZING: absolute
DIE_AREA: [0, 0, 60, 180]
CORE_AREA: [0, 0, 60, 180]